site_name: Compose Forms

# Repository
repo_name: 'Compose Forms'
repo_url: 'https://github.com/keygenqt/compose-forms'

# Navigation
nav:
  - 'Overview': index.md
  - 'State TextField': stateTextField.md
  - 'Validation': validationTextField.md
  - 'Systematization': systematizationTextField.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'black'
    accent: 'deep orange'
  font:
    text: 'Roboto'
    code: 'JetBrains Mono'